version: "3.2"
services:
  django-server:
    build: ./src/django-server/
    ports:
        - "8000:8000"
    working_dir: /usr/app
    volumes:
        - ./src/django-server:/usr/app
    command: python3 manage.py runserver 0:8000
    environment:
      - SECRET_KEY=qo%)b!!w_yuf$k7w_-%k33utma@10-p%do9*2n3n1b(0+ok*e+
    tty: true

  express-server:
    image: node:8
    working_dir: /usr/app
    volumes:
      - ./src/express-server:/usr/app
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"
    environment:
      - TS_NODE_CACHE_DIRECTORY=/tmp
    tty: true

  sinatra-server:
    image: ruby:2.4
    working_dir: /usr/app
    volumes:
      - ./src/sinatra-server:/usr/app
    command: bash -c "bundle install && bundle exec shotgun --server=thin --port=9292 --host=0.0.0.0 config.ru"
    ports:
      - "9292:9292"
    tty: true

  e2e:
    image: node:8
    working_dir: /usr/app
    volumes:
      - ./src/e2e:/usr/app
    command: bash -c "npm install && npm test"
    links:
      - django-server
      - express-server
      - sinatra-server
    environment:
      - TS_NODE_CACHE_DIRECTORY=/tmp
      - DJANGO_SERVER_HOST=django-server
      - EXPRESS_SERVER_HOST=express-server
      - SINATRA_SERVER_HOST=sinatra-server
