version: "3.2"
services:
  django-server:
    build: ./src/django-server/
    ports:
        - "8000"
    working_dir: /usr/app
    volumes:
        - ./src/django-server:/usr/app
    command: python3 manage.py runserver 0:8000
    environment:
      - DEBUG=false
      - SECRET_KEY=859a3dc54ede5dbf4f10d9fcb2ff23f0b0bf9a3bfc6f74e2456f1596d80db87af5da2be1bd4952f430e510656cddf3f4d115
    tty: true

  express-server:
    image: node:10
    working_dir: /usr/app
    volumes:
      - ./src/express-server:/usr/app
    command: bash -c "npm install && npm start"
    ports:
      - "3001:3000"
    environment:
      - TS_NODE_CACHE_DIRECTORY=/tmp
    tty: true

  sinatra-server:
    image: ruby:2.4
    working_dir: /usr/app
    volumes:
      - ./src/sinatra-server:/usr/app
    command: bash -c "bundle install && bundle exec shotgun --server=thin --port=9292 --host=0.0.0.0 config.ru"
    ports:
      - "9292"
    tty: true

  react-antd-js-client:
    image: node:10
    working_dir: /usr/app
    volumes:
      - ./src/react-antd-js-client:/usr/app
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"
    links:
      - express-server
    tty: true

  e2e:
    image: node:8
    working_dir: /usr/app
    volumes:
      - ./src/e2e:/usr/app
    command: bash -c "npm install && npm test"
    links:
      - django-server
      - express-server
      - sinatra-server
    environment:
      - TS_NODE_CACHE_DIRECTORY=/tmp
      - DJANGO_SERVER_HOST=django-server
      - EXPRESS_SERVER_HOST=express-server
      - SINATRA_SERVER_HOST=sinatra-server
    tty: true
